# -*- coding: utf-8 -*-
"""Dijkstra's Algorithm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XkOqT3Szs2Iro5SVDr8hnPcANcn7ZqF3
"""

#dijkstra algo implementation     Dynamic programming         Shortest path problem




nodes = [0,1,2,3,4,5]          #nodes in a graph

edges = {(0,1):1,
         (0,2):1.5,
         (0,3):2,
         (2,3):1.5,
         (1,4):2.5,
         (1,3):0.5,
         (3,5):1,
         (4,5):2
}